### PR TITLE
* Sun May 10 2015 stephane de Labrusse <stephdl@de-labrusse.fr> - 1.0…

### PR DESCRIPTION
**Pull request by stephdl**
….1-2.ns6
- Add an input box to change TCPPort in nethgui
- Switch to the new mock standard

### CODE REVIEW

**Comment by DavidePrincipi** [comment]
We usually do not allow changing the service port from the server manager. @gsanchietti, @alefattorini  , @filippocarletti What do you think?

**Comment by stephdl** [comment]
At first I was started to edit the documentation and do a PR about it, since any dude can do it and I'm training in Nethgui, I thought that it will be more valuable to allow simply the sysadmin to change the udp/tcp port of services.

Therefore, either you document it or you allow the change in Nethgui, for now none are done .

It's a Bug

Moreover If you hide these settings, quickly hackers will come...Hey my friend he gets a NethServer, lets start the attack on common port :)

If the problem of contribute to the core code is about licensing, my works yesterday were in WTFPL (http://www.wtfpl.net/)

:)

good afternoon

**Comment by filippocarletti** [comment]
Not exposing the port on the interface is SME Server heritage: we forked, we can change policy, but I'd like to involve different kind of users in the decision.
Putting my feet in the shoes of a sysadmin which doesn't know what a port is, I'd like to document the commands to change the port setting, as if docs were for advanced configurations.
At the same time, I, knowing the meaning of "port", feel convenient having the settings there in the server-manager.
I think that the question we should ask ourselves is:
can a "casual user" break something changing the port?
If the answer is yes, we should hide the setting from the interface.
If a setting change a behaviour but doesn't break things we can expose it in the interface. I know that the line between break and change is thin and that we could find many examples of settings that we have in the server-manager that could break things.
As an example closely related to "port", we do not only offer the option to change, but we suggest to change the ssh port.
Honestly, I don't want to take this decision alone, I'd like to involve the community.
Let's move this thread to the forum.

Stephane, I put you in the group of expert sysadmin with me. :-)

**Comment by alefattorini** [comment]
> Let's move this thread to the forum

Indeed, please keep all discussions into one place :-)
Steph, could you copy/paste it?

**Comment by filippocarletti** [comment]
I'll do it.

**Pull request closed without merging**
